language: php
dist: bionic
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly
before_install: composer self-update
install: npm install
script: npm test
jobs:
  allow_failures:
    - php: nightly
  include:
    - name: Lint
      script: npm run lint
    - name: cacert.pem current
      script: tests/scripts/cacert.sh
cache:
  directories:
    - $HOME/.composer/cache/files
